# Generated by Django 3.2.3 on 2022-09-18 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.TextField(default='English', max_length=1000),
            preserve_default=False,
        ),
    ]
