# Generated by Django 3.2.3 on 2022-09-18 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_book_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.TextField(max_length=1000, verbose_name='Language'),
        ),
    ]
